const AUTH_REDUX_CONSTANTS = {
  LOGIN_USER: 'LOGIN_USER',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  LOGOUT_USER: 'LOGOUT_USER',
};
export default AUTH_REDUX_CONSTANTS;
