const AUTH_REDUX_CONSTANTS = {
  LOGIN_USER: 'LOGIN_USER',
  CHANGE_USER_PROFILE_IMAGE: 'CHANGE_USER_PROFILE_IMAGE',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  USER_LOGOUT: 'USER_LOGOUT',
  CONFIGURE_2FA: 'CONFIGURE_2FA',
};
export default AUTH_REDUX_CONSTANTS;
