const DASHBOARD_REDUX_CONSTANTS = {
  SUBSCRIPTION_CHART_DATA: 'SUBSCRIPTION_CHART_DATA',
  COMPANY_SIZE_CHART_DATA: 'COMPANY_SIZE_CHART_DATA',
  GENDER_CHART_DATA: 'GENDER_CHART_DATA',
  TOP10_INDUSTRIES_DATA: 'TOP10_INDUSTRIES_DATA',
  DEAL_VALUES_DATA: 'DEAL_VALUES_DATA',
  OPPORTUNITY_STAGES: 'OPPORTUNITY_STAGES',
};
export default DASHBOARD_REDUX_CONSTANTS;
