const DASHBOARD_REDUX_CONSTANTS = {
  SUBSCRIPTION_CHART_DATA: 'SUBSCRIPTION_CHART_DATA',
  COMPANY_SIZE_CHART_DATA: 'COMPANY_SIZE_CHART_DATA',
  GENDER_CHART_DATA: 'GENDER_CHART_DATA',
  TOP10_INDUSTRIES_DATA:'TOP10_INDUSTRIES_DATA',
};
export default DASHBOARD_REDUX_CONSTANTS;
