const QUOTE_REDUX_CONSTANTS = {
  ALL_QUOTE: 'ALL_QUOTE',
  DELETE_QUOTE: 'DELETE_QUOTE',
  ADD_QUOTE: 'ADD_QUOTE',
  UPDATE_QUOTE: 'UPDATE_QUOTE',
  SET_SELECTED_QUOTE_DATA: 'SET_SELECTED_QUOTE_DATA',
  // QUOTE_STATUS: 'QUOTE_STATUS',
};
export default QUOTE_REDUX_CONSTANTS;
